"""Profile Migration

Revision ID: 48af70969916
Revises: 3ed84ca2a1cc
Create Date: 2022-03-09 12:03:29.177304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48af70969916'
down_revision = '3ed84ca2a1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
