"""Modify Migration

Revision ID: 630db200a37c
Revises: 732791999e52
Create Date: 2022-03-09 20:20:43.831438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630db200a37c'
down_revision = '732791999e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
