"""Delete Migration

Revision ID: 732791999e52
Revises: 8de688490f58
Create Date: 2022-03-09 20:19:40.625985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732791999e52'
down_revision = '8de688490f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
